[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Handle form submissions
[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/quote"  
  to = "/quote/"
  status = 301

# Handle trailing slashes for SEO
[[redirects]]
  from = "/areas/*"
  to = "/areas/:splat/"
  status = 301

[[redirects]]
  from = "/guides/*"
  to = "/guides/:splat/"
  status = 301

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Forms configuration
[forms]
  settings = true
